### ISSUE TITLE
🔧 Make mypy and doc string linters opt out instead of opt in

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#1001]
### Proposed refactoring

To improve our code quality we started to use `mypy` and docstring linters on more and more sub packages.
We are now at a point where it might be easier to those tools opt out for the packages that aren't ready, instead of opt in for the packages that we already use them on.

Currently checked sub packages:
- plugin_system
- utils
- deprecation
- testing
- parameter
- project
- model/property.py
- builtin/io/pandas

Currently **NOT** checked sub packages:
- io (should be no problem)
- typing (should be no problem)
- analysis (needs type stubs and docstrings)
- builtin (needs type stubs  and docstrings for megacomplexes, io needs more annotations and docstrings)
- cli (?)
- model (needs type stubs and docstrings)

### Benefits

- [x] Makes code easier to maintain
- [x] Documents the user facing API
- [x] Mypy will find a lot of problem we didn't discover yet (unused code paths)

**Comment by jsnel** [comment]
I think we already made a lot of progress towards this, could you re-evaluate how far we are from achieving this @s-weigand ?

**Comment by jsnel** [comment]
I think we already made a lot of progress towards this, could you re-evaluate how far we are from achieving this @s-weigand ?
