### ISSUE TITLE
✨ Add compression ability for netcdf plugins `save_dataset`

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#1035]
### Is your feature request related to a problem? Please describe.

We recently had a problem in the examples repository where we couldn't update the "gold standard" to compare result consistency since the DOAS result was over 100MB (GitHub limit at which you are forced to use git LFS).

We could shave off 40MB by using compression for `*.nc` files, which required reading and rewriting the files.

### Describe the solution you'd like

I would like for the netCDF plugin implementation to take a keyword argument `compression_level: int | None=None`.
We could propagate this down from `save_result` to `save_dataset` by using `SavingOptions` which only trigger if `SavingOptions.data_format == nc`.

### Describe alternatives you've considered

The current workaround is to read the file in and overwrite it with the compressed version.

### Additional context

As discussed with @joernweissenborn before we aren't 100% sure if other plotting software like OriginLab is compatible with compression. So we would need some tester for that.

I prepared 2 datasets for testing (dummy data from the quickstart)
[nc-compression.zip](https://github.com/glotaran/pyglotaran/files/8358493/nc-compression.zip)

The compressed version was generated from this code
![image](https://user-images.githubusercontent.com/9513634/160300898-fd95f4d3-62be-4731-88b2-4c88743129e1.png)

@ism200 @fjthephysiker Since you got an OriginLab could you be so kind and confirm that reading the compressed version works? 🙏

**Comment by jsnel** [comment]
There's also something like downloading a trial version of the latest version (7 days). 
Anyways, both formats can be read/imported.

Data -> Connect to file -> NetCDF
![image](https://user-images.githubusercontent.com/3616369/160302416-fb5e976c-b4d3-4b6a-af48-c3b7b54be665.png)

Evidence screenshot below:

![image](https://user-images.githubusercontent.com/3616369/160302384-1fa72f06-12b4-4d5a-b94c-457c241e9281.png)

**Comment by s-weigand** [comment]
@jsnel Thanks a lot for testing

**Comment by jsnel** [comment]
Given that the compressed files can be easily read by other tools such as origin, and we know we can work with it from using it for a while now for our gold-standard results [see run_examples.py](https://github.com/glotaran/pyglotaran-examples/blob/12971ca3c1e92cacdb783457cc41f34b0827d244/scripts/run_examples.py#L38) I think we can activate it by default.

**Comment by s-weigand** [comment]
Here is a quick benchmark and file size comparison, even `lvl1` compression is about `15 times slower` than no compression
As for the file size, the difference between the different levels is neglectable and might only be worth it if you need to get under a specific threshold.
![image](https://user-images.githubusercontent.com/9513634/200194789-f01569af-69a5-433c-bab6-7f09fc2e57bf.png)

**Comment by jsnel** [comment]
Thanks for investigating, ok, so we can add compression_level as an option, but should not make it the default.
