### ISSUE TITLE
♻️ Update result comparison standard with each minor release 🚇

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#1045]
### Summary

Change the 'gold standard' result comparisons reference (integration test reference) with every minor release (provided that all integration tests are passing leading up to the release), to ensure that the new integration tests introduced with each release can be easily compared with future released.

### Introduction

Since the release of pyglotaran [v0.3.0 ](https://github.com/glotaran/pyglotaran/releases/tag/v0.3.0) a modest collection of 'examples' or 'integration tests' has been used to maintain existing functionality and safeguard against regressions. These examples have lived in the pyglotaran-examples repository (e.g. for [v0.3.0](https://github.com/glotaran/pyglotaran-examples/tree/v0.3.0/pyglotaran_examples)). 

With PR #760 this was formalized into a result comparison framework, meaning that with every change released onward from 0.4.0 the result output from running the pyglotaran-examples are automatically compared to a 'gold standard' reference (starting with [0.4.1](https://github.com/glotaran/pyglotaran/releases/tag/v0.4.1)).  See the [v0.4.1 release notes](https://github.com/glotaran/pyglotaran/releases/tag/v0.4.1) for more details.

### Problem

As new features are added, new integration tests are needed to validate and maintain the new functionality. However, the code that set the gold standard is not able to run the new integration tests (after all, new code was added for the feature). For instance, the ✨ Damped Oscillation Megacomplex (a.k.a. DOAS) feature was added in [PR-764](https://github.com/glotaran/pyglotaran/pull/764) and released in v0.5.0. So not part of the v0.4.1 feature set, or integration tests. 

Also it is possible that due to refactoring or usability improvements, the way output is stored is changed, resulting in the need for backports and regenerating of validation results which means more burden on maintainers. 

### Proposed solution

With every minor release, the gold standard set of examples, integrations tests or validation tests is updated to the latest release.

### Benefits

- [ ] Ensures functionality introduced in one minor version, can be tested in the next minor release
- [ ] Reduced burden on the maintainer
- [ ] Gold standard stays relevant, can evolve which the package.

**Comment by s-weigand** [comment]
Sounds good to me.
But got googleability I would use `GEP` instead of `pEP` since the search is case insensitive.
