### ISSUE TITLE
Problem with loading of ascii file💬 

### ISSUE THREAD

**Issue by jakubslawski** [glotaran/pyglotaran#1106]
Hi, I'm trying to use GUI version of Glutaran (1.5.1). I formatted my dataset as time explicit data file (txt file in the attachment). However, after opening it in Glotaran, it's not displayed correctly: time and wavelength points are just subsequent integer numbers (screenshot in the attachment). It seems to read a line with time delays as data points. I've tried different file formats (dat, ascii, txt), delimiters (comas, tabs), number formats, etc. Still without correct effect.
I would be grateful for your help and tip how exactly format data files to be properly read by Glotaran.
Thanks in advance.
![1](https://user-images.githubusercontent.com/79151400/178734755-91beea36-a487-4045-b3e5-7908b5bed4a2.png)
[data.txt](https://github.com/glotaran/pyglotaran/files/9102123/data.txt)

**Comment by s-weigand** [comment]
Hi @jakubslawski this question would rather belong in the [repository of the legacy software](https://github.com/glotaran/glotaran-legacy/issues) 😉 

The specs for the glotaran-legacy `ascii` file format can be found in the [documentation of the legacy software](https://glotaran.org/wiki.html).

That said you can use `pyglotaran` to read in your data and save them in the correct format.

```python
import pandas as pd
import xarray as xr

from glotaran.io import save_dataset

data = pd.read_csv("data.txt", sep="\s+", skiprows=4)
dataset = xr.DataArray(data.values[:,1:], coords={"spectral": data.values[:,1], "time": pd.to_numeric(data.columns[1:])})

save_dataset(dataset.T, "data.ascii")
```

Which would give you the following file (extension `.txt` added to upload directly to github)
[data.ascii.txt](https://github.com/glotaran/pyglotaran/files/9112671/data.ascii.txt)

I think the added 0 in the time axis was the problem (see `pd.to_numeric(data.columns[1:]`)

Depending on what your original data are you could also directly load them with `pyglotaran` (no extra transformaions needed).

If this solves your problem feel free to close the issue.

**Comment by jakubslawski** [comment]
Hi Sebastian,
Thank you for your response. I used your code and had to change one of the indices (to take column of index 0 as spectral coordinates):
`dataset = xr.DataArray(data.values[:,1:], coords={"spectral": data.values[:,0], "time": pd.to_numeric(data.columns[1:])})`
and now it works perfectly. I'm closing the issue.
Thanks!
