### ISSUE TITLE
Glotaran plotting helper class is needed 

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#114]
We need a simple way to visualize the results from an analysis

Methods that generate a single plot where it makes sense (spectra and/or concentration profiles), or a collection of subplots where it makes sense (svd, overview). 
e.g. (to be worked out) 
gta.plot(result).overview()
gta.result.plot_residual() plot_svd_residual()
gta.result.plot_EAS() plot_DAS() plot_SAS()

**Comment by joernweissenborn** [comment]
There are enough plotting tools ut there.
