### ISSUE TITLE
♻️ Refactor class inheritance so child classes don't have unused/ignored attributes

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#1154]
### Proposed refactoring

Due to inheritance and a discrepancy between the special and general cases in a mathematical sense vs. class inheritance point of view, we have some child classes with have unused attributes.
E.g. [`IrfGaussian`](https://github.com/glotaran/pyglotaran/pull/1135#discussion_r1004880767) and [`IrfSpectralGaussian`](https://github.com/glotaran/pyglotaran/pull/1135#discussion_r1004881825)

### Benefits

- [x] Makes code easier to maintain
- [x] Improved readability of the code
- [x] Simplifies the user facing API

**Comment by jsnel** [comment]
@s-weigand is this resolved with #1135 ? If not, can you assign a milestone?

**Comment by s-weigand** [comment]
@joernweissenborn said that this will be fixed by the planned deprecation of the `decay` megacomplexes in favor of `kinetic` megacomplexes.
For `pyglotaran-model-language` I will implement it the correct way, so `IrfGaussian` won't show the ignored `scale` argument as autocompletion.
