### ISSUE TITLE
📚 Rewrite quickstart to use pyglotaran_extras

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#1252]
### Version information

`0.7.0.dev` and below

[Quickstart/Cheat-Sheet](https://pyglotaran.readthedocs.io/en/v0.6.0/notebooks/quickstart/quickstart.html)

### Describe the issue

Right now the `Quickstart/Cheat-Sheet` demonstrates how to plot using the bare `xarray` interface.
The `pyglotaran_extras` were created to get a quick and convenient feedback about the results the parameter estimation yields and not dwell on data selection, xarray datastructure and matplotlib plotting refinement details, also well all allowing plot refinement after using one of those convenience functions.
So the quickstart promotes a workflow that has an unnecessarily steep learning curve and most users won't use after.

### Expected documentation

A quickstart that demonstrates an actual user workflow, not blanking out on the existence of `pyglotaran_extras`.
We have an ecosystem and `pyglotaran` does not exist in a vacuum no shame in promoting other parts of the ecosystem if that makes user life easier.

**Comment by jsnel** [comment]
Will get around to this eventually, keep open as a reminder.
