### ISSUE TITLE
Create Distribution

### ISSUE THREAD

**Issue by joernweissenborn** [glotaran/pyglotaran#13]
- [x] Determine packaging requirements.

pyglotaran is distributed on pypi and conda-forge

- https://pypi.org/project/pyglotaran/
- https://anaconda.org/conda-forge/pyglotaran

Other forms of distribution can be considered but are outside of the scope of this issues (that is the standard form of distribution). For any other distribution a separate issue would have to be raised.

Distribution options, in addition to usage documentation and examples:
1. Distribute only the package with its built-in CLI
2. Distribute the package along with a notebook front-end (e.g jupyterlab)
3. Distribute the package along with -examples package and notebook front end
4. Distribute the CLI tool (`pyglotaran[cli]`) along with basic plot functionality (`pyglotaran[plot]`) or similar
5. Distribute a full-fledged Qt GUI

**Comment by jsnel** [comment]
Maybe we should look into using [Beeware](https://beeware.org/)'s [Briefcase](https://beeware.org/project/projects/tools/briefcase/).

**Comment by s-weigand** [comment]
This might also be useful.
https://github.com/conda/constructor

**Comment by jsnel** [comment]
Also of interest may be:
- https://github.com/Nuitka/Nuitka
- https://www.pyinstaller.org/
For point 5 (Qt GUI):
- https://github.com/Wanderson-Magalhaes/PyOneDark_Qt_Widgets_Modern_GUI

**Comment by jsnel** [comment]
The current standard is distribution via [pypi](https://pypi.org/project/pyglotaran/) and [conda-forge](https://anaconda.org/conda-forge/pyglotaran), for another form of distribution (e.g. in a stand-alone CLI or GUI) a sperate issue would have to be created.
