### ISSUE TITLE
🧹 Switch back to GeekyEggo/delete-artifact

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#1439]
In PR #1436 we switched to a fix branch of a fork of [`GeekyEggo/delete-artifact`](https://github.com/GeekyEggo/delete-artifact) to get around [the following error](https://github.com/glotaran/pyglotaran-extras/actions/runs/8296291449/job/22705133508):
```
Error: HttpError: Resource not accessible by integration
```

After the [fix is merged](https://github.com/GeekyEggo/delete-artifact/pull/24) we should switch back to the upstream action.

**Comment by jsnel** [comment]
The upstream fix has been merged in.

**Comment by s-weigand** [comment]
Closed via #1441
