### ISSUE TITLE
Jupyter notebook of the pyGlotaran is not available from the link provided in the paper 

### ISSUE THREAD

**Issue by SanjoyPatraIISc** [glotaran/pyglotaran#1452]
### Version information

[Documentation Section](link_to_the_docs)
https://github.com/glotaran/pyglotaran-releasepaper-supplementary-information/releases

This link seems not to be working.

**Comment by s-weigand** [comment]
Thanks for pointing out this issue!
It seems there was a typo in the link where a dash is missing between `release` and `paper`.
This is the correct link:
https://github.com/glotaran/pyglotaran-release-paper-supplementary-information/releases

**Comment by s-weigand** [comment]
I did a temporary rename of the repository to the version without the dash and now the old link also properly redirects.
Thanks again @SanjoyPatraIISc

**Comment by SanjoyPatraIISc** [comment]
Thanks for the correction.
It is working fine now.
