### ISSUE TITLE
Update user documentation with instruction to get to a demo state

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#146]
If I currently follow the user documentation instructions on installation and usage I do not end up in a state where I would e.g. be able to execute a test notebook. 

### The issue

Currently the only instructions are
``` python
pip install glotaran
import glotaran
```
and *then* what?

A user, following the instructions in the user manual, should be directly shown the evidence that the problem is verifiable working on his computer, because it's generating output which requires glotaran to work and gives the user visual feedback of this.

#### Minimal spec
Let the user execute a functional script which loads data, or simulates it, fits it and shows default plots for residual assessment and visualization of concentrations and estimated spectra.

#### Target spec
Extend the instructions with instruction to install jupyter lab, let the user open up a simple but functional notebook, which loads data (preferred) or simulates it, fits the data and shows default plots for residual assessment and visualization of concentrations and estimated spectra.

Plots needed are shown in  https://github.com/glotaran/glotaran-examples/tree/master/fluorescence/2001-Gobets_et_al-Streakdata_PSI
``

**Comment by s-weigand** [comment]
I guess that telling the users that after installing glotaran, they can get familiar with it exploring the examples. To verify that glotaran is fully functional we could ship the tests (numpy does that).

**Comment by joernweissenborn** [comment]
@jsnel Please update or close.

**Comment by jsnel** [comment]
One could argue that the quickstart in the docs (https://pyglotaran.readthedocs.io/) at least provides enough information to get started. Improvements can certainly be made but this can be addressed as a separate issue. In any case this issue is a bit stale.
