### ISSUE TITLE
Problem with IRF, Initial Concentrations and Peakposition

### ISSUE THREAD

**Issue by Husker2101** [glotaran/pyglotaran#147]
* glotaran version: 0.0.8
* Python version: 3.6.5
* Operating System:

### Description
-it seems that the IRF influence the Peakposition, depend on width and center and have Probles with      the initialconcentrations
-for a compartment s1(PBP) with initial concentration equal one, others(Chlf, Chla, Ionen) equal zero,
 the Peakpsition in the Spectrum t=0 is not the same in the Sum of the DAS-Graphs
- for t=0 you should only see only one Compartment:
[Problem01.tar.gz](https://github.com/glotaran/glotaran/files/2303417/Problem01.tar.gz)

 s1(PBP) = 1

### What I Did
see the notebook problem.ipynb
[Problem01.tar.gz](https://github.com/glotaran/glotaran/files/2303419/Problem01.tar.gz)

**Comment by joernweissenborn** [comment]
@jsnel  Please try to reproduce

**Comment by jsnel** [comment]
I will pick this up and see how the behavior is with the latest master.

**Comment by s-weigand** [comment]
We can't reproduce it because the API has changed that much that this example isn't valid code anymore.
Thus this issue will be closed.
