### ISSUE TITLE
integrate functionality of analysis.py to result class

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#172]
The functionality in glotaran/glotaran/models/spectral_temporal/analysis.py
retrieve_sas
retrieve_das
retrieve_coherent_artifact
retrieve_coherent_artifact_clp
should be in the result object, as in e.g:
result.retrieve_sas() or simply
result.sas 
result.retrieve_sas() should probably used with optional args.

There should also be the option to retrieve the concentration matrix (normalized and raw format), etc.

**Comment by joernweissenborn** [comment]
The result has all of this in the nc files.
