### ISSUE TITLE
Speedup test_kinetic_spectrum_model.py::test_kinetic_model[True-IrfDispersion]

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#228]
### Description
The test `glotaran/builtin/models/kinetic_spectrum/test/test_kinetic_spectrum_model.py::test_kinetic_model[True-IrfDispersion]` is very slow, which leads for travis to timeout. Maybe this can be solved by tweaking the inital parameters.

**Important:**
In order to make the conda release happen I had to temporarily deactivate that test (see #227).

**Comment by joernweissenborn** [comment]
This is not the problem of bad parameters since the max nr of function evaluation is fixed and the evaluation time also. There error lies somewhere else and is related to some things I changed. I need to investigate this further.

**Comment by joernweissenborn** [comment]
CC @jsnel

**Comment by jsnel** [comment]
Actually a lot of time was also spent on test_kinetic_image_model.py which is the job directly before it, this could be related to test timeouts.

**Comment by s-weigand** [comment]
While trying to release `pyglotaran` on `conda-forge` the tests did hang at 57% (`test_kinetic_spectrum_model.py` or `test_spectral_irf.py`) for over 40min the azure tests .
If I remember right, back then we did 'fix' it by changing the CI to github actions, which has much better hardware specs than travis or appveyor.
After we got `pyglotaran` on `conda-forge`, we should try to fix this or determine/set some kind of minimal hardware requirements.

**Comment by s-weigand** [comment]
After @jsnel reminded me how we do things in our tests, I 'Volks Wagened' the tests on `conda-forge` the same way we do here:
https://github.com/glotaran/pyglotaran/blob/03b69c10019426e495d039a1c3805d190ac8ef45/.github/workflows/CI_CD_actions.yml#L113

**Comment by s-weigand** [comment]
@jsnel Wanted to have a look at this because maybe the parameters are too far off.
That said we might already be fine with reactivating the test on the CI since we dropped `dask` which was responsible for most of the performance issues.
