### ISSUE TITLE
address xarray pandas warning

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#240]
Steps to reproduce:

- Open jupyter lab
- import glotaran
Observe warning:
python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)

----
Python 3.7.3
pandas                    0.25.2           py37he6710b0_0
xarray                    0.12.0                   pypi_0    pypi

**Comment by joernweissenborn** [comment]
Don't worry about that things, xarray will update together with pandas or shortly after. Nothing we can do instead nagging the xarray people about what they already know.
