### ISSUE TITLE
tests with IrfDispersion are failing on Travis; apply Volkswagen solution

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#245]
@joernweissenborn:
>  I am willing to simply fix this test for travis with https://pypi.org/project/pytest-vw/ and let the wheels be pushed by appveyor, which seems to have no problems

@jsnel 
> I agree

**Comment by joernweissenborn** [comment]
@s-weigand please make a commit to this branch hich moves the deployment to AppVeyor.

**Comment by s-weigand** [comment]
No VW solution, we get a Tesla with [GitHub Actions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions)
