### ISSUE TITLE
Model.py ate my homework!

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#252]
**Model from_dict deletes keys from input dict**

When calling <some_built_in_model>_from_dict(some_model_spec_in_dict_form) eventually the class method from_dict in model.py is invoked. 

This method, rather than taking a copy of the input works directly on the model_dict variable passed in by reference. It then iterates over the dict and uses 'del' to remove the keys it has added to the model, thus 'consuming' the dict as it goes along, see: 
https://github.com/glotaran/pyglotaran/blob/master/glotaran/model/model.py#L73

This is unwanted behavior. A user cannot expect a model_spec defined at the top level of a notebook to not be reusable simply because it was used in a model spec, if the same cell is invoked twice (not uncommen in a notebook settings) it will do something completely different. 

The simple solution would be to make a (deep?) copy of the model passed in by reference before working on it. See the follow gist for code which reproduces the problem:

https://gist.github.com/jsnel/b366398fb83cc25e5d92621e74a1c7b2

**Comment by s-weigand** [comment]
To be save that it also works properly with Mutables inside ok the dict you should use [`deepcopy`](https://pypi.org/project/enboard/)

**Comment by joernweissenborn** [comment]
This is WANTED behaviour and is desinged like this! The goal is to later
check if the dict is empty and if not tell users that some parts of the
yaml werent recognized, propably by spell checking. Make a copy of dict
before parsing and you are fine (I hacked around this in a the equal area
test).

Am Sa., 16. Nov. 2019 um 06:59 Uhr schrieb Joris Snellenburg <
notifications@github.com>:

**Comment by jsnel** [comment]
It seems to me the commit I did before both of your comments solves the user-side issue in the way you both suggested:  
https://github.com/glotaran/pyglotaran/commit/65121eeadd3bd3b4864e2978d1c5441d9c8e5e1b
(Yes, I understand consuming the dict is not a bug, but a feature, but this can also be done on a copy rather than a passed reference; that was the issue that resulted in a user-experienced bug).

The commit that fixes this issue was supposed to be a PR to the fix_performance branch but accidentally became a direct commit to it instead. The bug is not yet marked as fixed because it hasn't yet been merged into master.
