### ISSUE TITLE
LinAlg runtime errors in test_spectral_penalties.py

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#271]
In the test
glotaran/builtin/models/kinetic_spectrum/test/test_spectral_penalties.py

the parameter object is used twice, once in an optimization with and once without penalty. The penalty parameters (presumably because unfixed) in the optimization call without penalty causes a LinAlg SingularMatrix error (which is caught so not observed during testing). 

Can be solved by doing a `parameter2 = copy.deepcopy(parameter)` and then `del(parameter2['pen'])`

**Comment by joernweissenborn** [comment]
Did you solved it yet?
