### ISSUE TITLE
clps amps set to 0 if spectral_relation interval doesn't extend the spectral range

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#272]
See this commit:
https://github.com/glotaran/pyglotaran/commit/efda515659fa0b7055c567ccaf74bf5d34b92229
in the test modified glotaran/builtin/models/kinetic_spectrum/test/test_spectral_penalties.py
(extending the 'wavelength' from 1 to 10)
I run into 2 problems:

1. if the spectral_relation does not include all wavelengths the amplitude of the spectra outside is set to 0, instead of estimated freely
2. if the interval for equal_area_penalties is not identical to spectral_relations there is a crash

**Comment by joernweissenborn** [comment]
That's interesting. I suggest you hunt this bugs yourself because it will give you a good understanding how the whole relation and extra penalty framework works. I guess 1 is a stupid bug and 2. is a follow up bug because of this
