### ISSUE TITLE
inclusion of reduced K_matrix in the output  

### ISSUE THREAD

**Issue by AvratanuBiswas** [glotaran/pyglotaran#273]
* glotaran version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by joernweissenborn** [comment]
It has to be added in [here](https://github.com/glotaran/pyglotaran/blob/master/glotaran/builtin/models/kinetic_image/kinetic_image_result.py#L58).

@jsnel Are you up for that?

**Comment by jsnel** [comment]
@AvratanuBiswas could you update the issue description with a bit more info as to how you would expect it to work, and how you would test that it works. If you have a specific test case in mind (an analysis where you are currently missing that output) please use that to formulate a test case which would allow us to determine if the feature is working correctly.

**Comment by AvratanuBiswas** [comment]
@jsnel the reduced K-mat as an output will be useful for the nodal diagrams ( box-diagram to show energy transfer within compartments).

**Comment by AvratanuBiswas** [comment]
Thanks! The reduced k matrix is now there in the output for use.

**Comment by joernweissenborn** [comment]
We decided that this PR is good time to add some Tests for multiple
megacomplexes.

Am Do., 5. Dez. 2019 um 18:18 Uhr schrieb Avratanu Biswas <
notifications@github.com>:

**Comment by jsnel** [comment]
No need to close the issue, that will happen when the relevant commit (together with some additional tests) is merged into master.

**Comment by AvratanuBiswas** [comment]
@joernweissenborn  that will be a good test indeed, I'll start with one of old analysis for a test run.

**Comment by joernweissenborn** [comment]
@AvratanuBiswas We talk here about Unit tests, this are completly generic things which have no scientific meaning. Those are ment to be run by robots that to ensure that if the model and the math is sound, everything work and we will not have strange windows bugs or so. Thanks very much for your offer to create some, but this something I and @jsnel have to do.
