### ISSUE TITLE
Implement a new PID c-matrix generator

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#28]
PID stands for Proportional-Integral-Derivative and is a negative feedback loop system resulting in a damped oscillation around a certain setpoint. Implementation details will follow ....

Issue requested by Alfred. For more info see
https://github.com/ivmech/ivPID
and
https://www.cds.caltech.edu/~murray/courses/cds101/fa04/caltech/am04_ch8-3nov04.pdf

**Comment by joernweissenborn** [comment]
Please clarify.

**Comment by jsnel** [comment]
How would a plugin specification for this look like?

**Comment by jsnel** [comment]
Closed for lack of interest, can be reopened in the future if interest in this kind of functionality rekindles.
