### ISSUE TITLE
Plotting time-resolved traces with Lin-log time axis

### ISSUE THREAD

**Issue by earik87** [glotaran/pyglotaran#295]
* glotaran version:
* Python version: Python 3
* Operating System: Windows & Mac

### Description

In time-resolved spectroscopy, kinetic traces can have a very long time-axis. For visualization purposes, time - axis needs to be divided into linear (around excitation moment) and logarithmic (for long excitation times). I am not sure if this already exists in pyglotaran, otherwise I am willing to solve this issue.

### What I Did

Few months ago, I wrote Python code in Jupyterlab to plot such a linlog kinetic trace. You can reach the details and code of this project via the link below.
https://github.com/earik87/linear-logarithmic-axis-plotting

**Comment by jsnel** [comment]
Thank you for your contribution Enis! We will look into how to best make this kind of functionality available to the users. 

Would your solution be similar to one of the answers to a related question on Stackoverflow and/or did you further enhance the code? 
https://stackoverflow.com/questions/21746491/combining-a-log-and-linear-scale-in-matplotlib  
Having this additional information would help users if they want to find more information about a particular piece of code such as this.

**Comment by earik87** [comment]
Hi Joris,

Yes, thats very similar to my code. There is no enhancement on top of that,
as it solves only single problem. But in the future, a global variable can
be defined ( position on x-axis where linlog division occurs) as an
enhancement.

Kind regards,
Enis

**Comment by joernweissenborn** [comment]
See pyglotaran-exxtras
