### ISSUE TITLE
test_spectral_irf.py goes into infinite loop 

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#296]
* glotaran version: 0.0.15 (76d0a93cd587347c674fde20c04ba87c33628f47)
* Python version: Python 3.7.6 installed through Anaconda
* Operating System: Linux dustbin 5.4.14-2-default #1 SMP Thu Jan 23 08:54:47 UTC 2020 (fc4ea7a) x86_64 x86_64 x86_64 GNU/Linux
* Virtual Environment: conda create --name pyglotaran_37_dev python=3.7 pip wheel setuptools bump2version numpy scipy click cloudpickle dask[bag] lmfit numba pyyaml xarray netCDF4 Sphinx sphinx_rtd_theme numpydoc sphinx-autodoc-typehints matplotlib IPython tox flake8 pytest pluggy pytest-cov pytest-runner pytest-benchmark --no-default-packages

### Description

run glotaran/builtin/models/kinetic_spectrum/test/test_spectral_irf.py
It immediately goes into an infinite (wait) loop and never returns.

### What I Did

See this gist for the stack trace log:
[stack trace](https://gist.github.com/jsnel/504bce39619b5d9ec0232f1205aca380)

**Comment by jsnel** [comment]
Dask seems to freeze whenever this run time error occurs:

```
~/anaconda3/envs/pyglotaran_37_dev/lib/python3.7/site-packages/lmfit/minimizer.py:786: RuntimeWarning: invalid value encountered in sqrt
  (par.stderr * sqrt(self.result.covar[jvar, jvar])))
~/anaconda3/envs/pyglotaran_37_dev/lib/python3.7/site-packages/lmfit/minimizer.py:779: RuntimeWarning: invalid value encountered in sqrt
  par.stderr = sqrt(self.result.covar[ivar, ivar])
```

After adding some print statement it seems that in that case nans come out of the calculation.
```
Function evaluations 1, initial cost 1.3058e-31, final cost 1.3058e-31, first-order optimality 5.26e-17.
400
2.8287245887793094e-17
~/anaconda3/envs/pyglotaran_38_dev/lib/python3.8/site-packages/lmfit/minimizer.py:787: RuntimeWarning: invalid value encountered in sqrt
  (par.stderr * sqrt(self.result.covar[jvar, jvar])))
2.2130445756957464e-17
2.1247555045574334e-17
~/anaconda3/envs/pyglotaran_38_dev/lib/python3.8/site-packages/lmfit/minimizer.py:779: RuntimeWarning: invalid value encountered in sqrt
  print(sqrt(self.result.covar[ivar, ivar]))
nan
~/anaconda3/envs/pyglotaran_38_dev/lib/python3.8/site-packages/lmfit/minimizer.py:780: RuntimeWarning: invalid value encountered in sqrt
  par.stderr = sqrt(self.result.covar[ivar, ivar])
nan
nan
```

**Comment by jsnel** [comment]
Even with those warnings pytest can complete:

pytest glotaran/builtin/models/kinetic_spectrum/test/test_spectral_irf.py

glotaran/builtin/models/kinetic_spectrum/test/test_spectral_irf.py ..                                                                                                                                                                                                   [100%]

---

> warnings summary 
> glotaran/builtin/models/kinetic_spectrum/test/test_spectral_irf.py::test_spectral_irf[MultiIrfDispersion]
>   ~/anaconda3/envs/pyglotaran_37_dev/lib/python3.7/site-packages/lmfit/minimizer.py:787: RuntimeWarning: invalid value encountered in sqrt
>     (par.stderr * sqrt(self.result.covar[jvar, jvar])))
> 
> glotaran/builtin/models/kinetic_spectrum/test/test_spectral_irf.py::test_spectral_irf[MultiIrfDispersion]
>   ~anaconda3/envs/pyglotaran_37_dev/lib/python3.7/site-packages/lmfit/minimizer.py:779: RuntimeWarning: invalid value encountered in sqrt
>     print(sqrt(self.result.covar[ivar, ivar]))
> 
> glotaran/builtin/models/kinetic_spectrum/test/test_spectral_irf.py::test_spectral_irf[MultiIrfDispersion]
>   /home/joris/anaconda3/envs/pyglotaran_37_dev/lib/python3.7/site-packages/lmfit/minimizer.py:780: RuntimeWarning: invalid value encountered in sqrt
>     par.stderr = sqrt(self.result.covar[ivar, ivar])

---
2 passed, 3 warnings in 1.93s

**Comment by jsnel** [comment]
Most of the time - but not always - it freezes at the
residuals[label] of the _create_result call in glotaran/analysis/optimize.py:58

But any call to dask.compute (in a async threaded manner) can trigger a freeze.

**Comment by jsnel** [comment]
Debugging this in MS Visual Code doesn't work quite well, Pycharm CE works only slightly better. 

VS Code you cannot pause the debugging, you can only interrupt the thread resulting in earlier posted stack track dumps. In Pycharm when you pause it will pause in a Thread-XX, with XX being some number, where a _handle_workers routine is running in an infinite while loop. 
The process is now receiving a stop condition. 

```python
    @staticmethod
    def _handle_workers(pool):
        thread = threading.current_thread()

        # Keep maintaining workers until the cache gets drained, unless the pool
        # is terminated.
        while thread._state == RUN or (pool._cache and thread._state != TERMINATE):
            pool._maintain_pool()
            time.sleep(0.1)
        # send sentinel to stop workers
        pool._taskqueue.put(None)
        util.debug('worker handler exiting')
```
It's most likely a race condition related to the Dask implementation, not something we can easily fix. It also seems from past experience that some Dask updates reduce the problem, and some updates make it worse (in terms of frequency of occurrence). It's also possible that Linux threading is more susceptible to this problem than e.g. Windows.
 
A possible workaround would be to set some sensible timeout value somewhere, preferably determined/scaled by the first iteration. Even better would be to do a graceful shutdown whereby the results from the last successful iteration are returned, rather than crash.

**Comment by jsnel** [comment]
This exception may be related:

> Exception ignored in: <function Pool.__del__ at 0x7f4b7e69e550>
> Traceback (most recent call last):
>   File "python3.8/multiprocessing/pool.py", line 268, in __del__
>   File "python3.8/multiprocessing/queues.py", line 362, in put
> AttributeError: 'NoneType' object has no attribute 'dumps'
Which most likely related to
https://github.com/dask/dask/issues/5806

And this was patched Feb 3rd:
https://github.com/dask/dask/commit/b3d2c2c50f24a9522c10528d9ee3f529492b3cef

**Comment by joernweissenborn** [comment]
fixed
