### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#297]
* glotaran version: 0.0.15

### Description

There are a bunch of open PR that should be updated, especially considering updating some dependencies may address and infinite wait loop.

### List of linked pull requests 

Update pandas to 1.0.1 
#294 opened 3 days ago by pyup-bot
Update dask to 2.10.1 
#293 opened 8 days ago by pyup-bot
Update xarray to 0.15.0 
#292 opened 9 days ago by pyup-bot
Update numba to 0.48.0 
#290 opened 9 days ago by pyup-bot
Update pyyaml to 5.3 
#286 opened on Jan 7 by pyup-bot
Update numpy to 1.18.1 
#285 opened on Jan 7 by pyup-bot
Update lmfit to 1.0.0 
#281 opened on Dec 21, 2019 by pyup-bot
Update scipy to 1.4.1 
#280 opened on Dec 19, 2019 by pyup-bot

**Comment by s-weigand** [comment]
Guess we should just close the Pyup PR's and use the dependabot ones instead.

**Comment by s-weigand** [comment]
Guess this can be closed ^^

**Comment by jsnel** [comment]
Indeed, dependencies have been updated in PRs: 
#302 #304 #308 #307 #306 #303 #312 #301
