### ISSUE TITLE
Implement IRF backsweep for analysis of streak camera data

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#32]
In order to correctly describe the kinetics or (Sub)-Picosecond Spectral Evolution of Fluorescence of a Synchroscan Streak-Camera System it is needed to take into account the so called backsweep resulting from the perculirarty of the instrument as explained [here:](https://github.com/glotaran/glotaran/blob/develop/tests/resources/papers/2008-van_Stokkum_et_al-Chapter_12_Streakdata_analysis.pdf)

In TIMP it is implemented in [calcCirf ](https://github.com/jsnel/TIMP/blob/master/pkg/R/calcCirf.R) as follows:
```
      if(streak) {
        backsweep <- getStreakBacksweep(streakT, k, mu,x)
        m <- m + backsweep
      }
```
where m is the result of the c matrix calculation.
The function getStreakBacksweep is implemented in [getStreakBacksweep.R](https://github.com/jsnel/TIMP/blob/master/pkg/R/getStreakBacksweep.R) as follows

```
"getStreakBacksweep" <- function(streakT, k, mu, x) {
	
	Y <- matrix(0,length(x),length(k))
	for(i in 1:length(k)) {
	      x1<-exp(-k[i]*(x-mu + streakT))
	      x2<-exp(-k[i]*((streakT/2) - (x-mu)))
	      x3 <- exp(-k[i]*streakT)
	      Y[,i] <- (x1+x2)/(1-x3)
	}
	Y
}
```

**Comment by joernweissenborn** [comment]
please update the thest to current API
