### ISSUE TITLE
Store model type and irf type as part of saved result object

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#320]
Currently in the stored result nc file, no information about the model type or irf type is stored. This information is useful (necessary to avoid a lot of business logic) to have to decide on which plot functions to call to visualize the output stored in the result object.

**Comment by joernweissenborn** [comment]
This will be solved by storing the model, see #766

**Comment by jsnel** [comment]
This is also something that should be solved by the new project infrastructure PR: #769

**Comment by s-weigand** [comment]
Closed in #841 since now we save the whole model
