### ISSUE TITLE
Use pre-commit-hooks

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#388]
# Description
I recently started using [`pre-commit`](https://pre-commit.com/), due to some project I contributed to.
And IMHO this would also be an improvement to the workflow for contributing  to `pyglotaran`.
I.e. this would prevent the infamous `fix flake8` commits.

## How does it work
Basically `pre-commit` installs [`git hooks`](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) which intercept the commit and runs the configured tests.
If all tests pass the commit succeeds, if a test fails the commit gets interrupted.
Those tests only run on the staged files, so if the commit isn't too massive they are done pretty fast (beside the first time it runs, since `pre-commit` sets up virtuals envs for each test).

**Comment by s-weigand** [comment]
Oh and [here is a post](https://blog.mphomphego.co.za/blog/2019/10/03/Why-you-need-to-stop-using-Git-Hooks.html) showing off some possible hooks.

**Comment by jsnel** [comment]
I invite you to file a PR @s-weigand  :)
