### ISSUE TITLE
Format code with black

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#389]
### Description
I would recommend using [black](https://github.com/psf/black) to format the whole code base in a uniform way.

### Why is this an issue?

Manually formatting code leads to inconsistencies in the code style (I can see who wrote this, by the style of the code), also it is additional manual labour which can be avoided.
Another bonus is that code formatters respect pep8, leading to less conflicts with `flake8` since formatting is none of your business.
Also code formatters can be used as a pre commit  hook (see #388) making it editor independent.

**Comment by jsnel** [comment]
Agreed on using black as a code formatting coupled with using pre-commit hooks, I invite you to make a PR @s-weigand.
