### ISSUE TITLE
Maybe change initial parameters for test_fitting[OneCompartmentDecay]

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#397]
### Description

As you might know, we have a PR from dependabot to upgrade `lmfit==1.0.1` (#377 ) which is blocked by failing tests.
Namely `test_fitting[OneCompartmentDecay]`.
After a `git bisect` (see below) I found that the change that broke this test happened somewhere in https://github.com/lmfit/lmfit-py/pull/610, but I couldn't find the responsible lines yet (most likely some change in the default value for `max_nfev` passed to `scipy.optimize`)

@joernweissenborn are you really sure that the initial parameter needs to differ one magnitude from the wanted result?

https://github.com/glotaran/pyglotaran/blob/7e4b176d59e0fc4f67f88cff1532517ad27b0102/glotaran/analysis/test/test_optimization.py#L89-L90

I.e. if you use:
```python
initial = ParameterGroup.from_list([30e-4])
```
Which already differs by a factor of about 3.3, the tests pass.

The tests also pass if you set the max steps to `nfev=10`.

https://github.com/glotaran/pyglotaran/blob/7e4b176d59e0fc4f67f88cff1532517ad27b0102/glotaran/analysis/test/test_optimization.py#L224

### What I Did
Maybe this is usefull for future reference.

- Checkout [my dummy branch](https://github.com/s-weigand/lmfit-py/tree/glotaran-lmfit-bisect)
- Make a new venv (i.e. `conda create -n "glotaran-lmfit-bisect" python=3.7`)
-  Change env (i.e. `conda activate glotaran-lmfit-bisect`)
- Install `lmfit` and `glotaran` in dev mode (`<your lmfit dir>/$ pip install -e .` and `<your glotaran dir>/$ pip install -e .`)
- Make sure you are in the lmfit dir `cd <your lmfit dir>`
- Reset the  one and only commit `git reset --soft b3753db1caff651a7ab4c818f0a3ca509e2b94b5`
- Start bisecting `git bisect start`
- Set lmfit 1.0.0 as last good point `git bisect good 1.0.0`
- Set lmfit 1.0.1 as bad point `git bisect bad 1.0.1`
- Run git bisect (`git bisect run python bisect_check.py`)

The result you should get is
```bash
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
10bd1320e233c9d576dd36f6428af556dda81021
0ba527c324ce9f68716dc4d8519180abd82fb868
a84ca3e98dcae2f451a304c8a55c0b9992c43900
3caab3b786bb74734a3f1b841af8d38f5c8e01c7
We cannot bisect more!
```

**Comment by s-weigand** [comment]
Also see #353

**Comment by jsnel** [comment]
The solution for fixing the tests in test_optimization is indeed to set nfev to a larger value, e.g. 10. 
The other failing test requires a code rewrite.
