### ISSUE TITLE
Use more customized exceptions

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#409]
### Description

While fixing issues with sonar cloud code quality assurance, I found that `pyglotran` mostly catches and throws the generic `Exception`.

i.e.:

https://github.com/glotaran/pyglotaran/blob/514962b2b7184cb2a01f9f335d54a5b257e47d3a/glotaran/model/model.py#L95-L96

The catching of generic `Exception` can lead to overlooking reasons why the code might break, and giving wrong error messages to the users.

Throwing the generic `Exception` isn't very helpful to the user and also leads to code duplication, since the error message is hardcoded.

The aboth example could be replaced with:
```python
class UnknownModelAttributeTypeError(TypeError):
   """Exception thrown if the Attribute type isn't known to the Model."""
   def __init__(self, item_type: str, name: str, *args, **kwargs):
         super().__init__(f"Unknown type '{item_type}' for attribute '{name}'")
```

And at the place in the code, it would simplify to:
```python
raise UnknownModelAttributeTypeError(item_type, name)
```

**Comment by jsnel** [comment]
Agreed. PR would be welcomed ;)

**Comment by jsnel** [comment]
There are currently (at least) 16 instances where general exceptions are raised, so this is still an issue. 
Not a v0.3.0 release blocker so added to the v0.4.0 milestone.

**Comment by joernweissenborn** [comment]
I think pure Exceptions are all out thanks to pre-commit.
