### ISSUE TITLE
Towards a useable API: making optimization object inspectable

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#440]
* glotaran version: 0.2.0-develop (feature_399)
* Python version: 3.6-3.9

### Description

Turning the optimizer into a (yielding) generator with inspectable properties at every iteration
- residual (SSE), progression up to current iteration
- SVD of residual
- estimated amplitudes (e.g. spectra) at each iteration
- concentration profiles at every iteration
 - tbd

**Comment by joernweissenborn** [comment]
I think that can all be doneSo the simplest way woud be to provide a way to get the `Problem` object of an optimization and then use parameter history. I will make a PR for this.

**Comment by s-weigand** [comment]
Related issues #233 #774 #819
