### ISSUE TITLE
Add verbose version information

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#441]
### Description
For reproducibility (especially given the scientific context) it would be good to add an easy way to get all the important environment information results were calculated with.
E.g. [qutip](https://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/examples/temporal-photon-scattering.ipynb#Software-version:) has a nice way of achieving this.

**Comment by jsnel** [comment]
Unfortunately too late to make it into v0.3.0 but I think important to implement before v0.4.0.

**Comment by s-weigand** [comment]
Since I need the same functionality for other projects as well I will have a look if there already is a tool for that and if not write one.

**Comment by s-weigand** [comment]
As a little side note.
For reproducibilities sake the version information (pyglotaran+runtime dependencies) should also be saved to the results.

**Comment by joernweissenborn** [comment]
@s-weigand what would you propose to get such info, is there a library for it that you know of?

**Comment by jsnel** [comment]
Also relevant: https://github.com/s-weigand/zenodo-cite

Should be addressed as part of the projects PR #769

**Comment by s-weigand** [comment]
We have basic version information and fine tuning with git shas and so on will come later maybe `0.7.0`

**Comment by jsnel** [comment]
Getting something done for this before December is a bit of a stretch, so moving it to the v1.0 milestone. With the idea, that the concept of reproducibility should be worked out by then, whether it is through logging or something else.
