### ISSUE TITLE
Refactoring TODOs

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#454]
### Description
Just a list of refactoring points we should tackle at some point and be aware of when adding new code.

- [x] Use `from typing import <type_name>` instead of `typing.<type_name>` for improved readability [see](https://github.com/glotaran/pyglotaran/pull/442#issuecomment-731253232)
- [x] Use `from typing import NamedTuple` instead of `from collections import namedtuple` so we can add typing [see](https://github.com/glotaran/pyglotaran/pull/442#issuecomment-731253232)
- [x] Use proper custom errors, for better readability and more flexibility [see](https://github.com/glotaran/pyglotaran/pull/442#issuecomment-731253232)
- [x] Use [`postponed annotations`](https://stackoverflow.com/a/61544901/3990615) pattern to colve circular dependency issues
- [x] Replace string types with [`postponed annotations`](https://stackoverflow.com/a/61544901/3990615) pattern e.g. [here](https://github.com/glotaran/pyglotaran/blob/617eb3bf1a0dd3ef37d23f3f3d7bc32fd5deee1a/glotaran/analysis/result.py#L65) or [here](https://github.com/glotaran/pyglotaran/blob/617eb3bf1a0dd3ef37d23f3f3d7bc32fd5deee1a/glotaran/parameter/parameter.py#L41)

**Comment by joernweissenborn** [comment]
Done, or @s-weigand

**Comment by s-weigand** [comment]
Done
