### ISSUE TITLE
♻️ Don't use None as default for required arguments

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#466]
* glotaran version: 0a3f5e23f5b3491054efc42b8b8e80643222af58
* Python version: 3.8.6
* Operating System: Win64

### Description

While writing type stub files for the runtime patched objects (Models and Modelattributes) due to [known limitations of mypy](https://github.com/python/mypy/wiki/Unsupported-Python-Features). I found that some functions have default value of `None` for arguments that are required. This suggests that you could use them without or fewer than required arguments.
Also, to make sense of the tracebacks the user needs detailed knowledge of the glotaran internals e.g. the model decorator.

### What I Did

The signature of the model decorator 
https://github.com/glotaran/pyglotaran/blob/0a3f5e23f5b3491054efc42b8b8e80643222af58/glotaran/model/decorator.py#L59-L76

suggests that you could use it like this to generate the most minimal (even so nonsensical) Model
```python
@model("foo")
class FooModel:
    pass
```

While the most minimal way for it not to crash is
```python
class DummyAttr:
    _glotaran_has_label = False

@model("foo", attributes={}, megacomplex_type=DummyAttr, matrix=lambda: None)
class FooModel:
    pass
```

Another instance where this is the case is in `kinetic_image_matrix`
https://github.com/glotaran/pyglotaran/blob/0a3f5e23f5b3491054efc42b8b8e80643222af58/glotaran/builtin/models/kinetic_image/kinetic_image_matrix.py#L11-L19

Where nearly all arguments are required but defaulted to `None`.

**Comment by s-weigand** [comment]
When talking to @joernweissenborn he explained that the idea behind `None` default values is to make them keyword arguments instead of positional ones.

A quick reminder on how 'normal' arguments work in python. They allow both the usage as keyword arguments **AND** positional arguments.
```python
In [1]: def f(x, y=1):
      :     return x + y
      :

In [2]: f(2)
Out[2]: 3

In [3]: f(x=2)
Out[3]: 3

In [4]: f(y=3, x=2)
Out[4]: 5

In [5]: f(1, 2)
Out[5]: 3
```

To force users to only use keyword arguments, for better readability (more verbose and unambiguous) e.g. for the `model` decorator this would make sense, we could use [keyword only arguments](https://www.python.org/dev/peps/pep-3102/)

```python
In [7]: g(2)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-3580407364ae> in <module>
----> 1 g(2)

TypeError: g() takes 0 positional arguments but 1 was given

In [8]: g(y=3, x=2)
Out[8]: 5
```

If we want users to only use positional arguments (the only reasonable use case, being not yet final argument names) we could use [positional only arguments](https://www.python.org/dev/peps/pep-0570/), since our new min version of python is 3.8

```python
In [2]: def h(x, y=1, /):
   ...:     return x + y
   ...:

In [3]: h(x=2)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-ad2c09c39c80> in <module>
----> 1 h(x=2)

TypeError: h() got some positional-only arguments passed as keyword arguments: 'x'

In [4]: h(2)
Out[4]: 3

In [5]: h(2, 3)
Out[5]: 5
```

Please note that those can also be mixed.

Here is also a nice video explaining how they work (just as a reference) 😉 
[![all python argument / parameter types](https://img.youtube.com/vi/aKCfCmSggPg/0.jpg)](https://youtu.be/aKCfCmSggPg)

**Comment by s-weigand** [comment]
__Just a Note__ (rev: f366ed6609b1276b705c34c84a935cc0d40cf8c6):
By now a minimal dummy model implementation (in my case for testing the plugin system) needs to look like this, to not throw an error when creating.

```python
class DummyAttr:
    _glotaran_has_label = False

@model(
    "foo",
    attributes={},
    megacomplex_type=DummyAttr,
    matrix=lambda: None,  # type:ignore
    model_dimension="",
    global_dimension="",
)
class FooModel:
    pass
```

https://github.com/glotaran/pyglotaran/blob/f366ed6609b1276b705c34c84a935cc0d40cf8c6/glotaran/model/decorator.py#L78-L95

**Comment by jsnel** [comment]
I think a lot of improvement toward this issue were incorporated in #1135, perhaps time for another review.
