### ISSUE TITLE
The devil is in the details

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#472]
* glotaran version: v0.2.0

### Description

The devil is in the details:
https://github.com/glotaran/pyglotaran/blob/master/glotaran/analysis/problem.py#L666
get consistent about what the grouped member/variable is, it is used as different things.

Also: 

Unify:  
[GroupedProblemDescriptor](https://github.com/glotaran/pyglotaran/blob/master/glotaran/analysis/problem.py#L36)
[ProblemDescriptor ](https://github.com/glotaran/pyglotaran/blob/master/glotaran/analysis/problem.py#L42)

Where data is manipulated, make a copy first: [data = data.copy()](https://github.com/glotaran/pyglotaran/blob/master/glotaran/analysis/problem.py#L278)

**Comment by joernweissenborn** [comment]
The code is actually correct. `problem.group` is the concatenated labels of the dasets (I added docstring in my latest PR). This used to look up the matrix for an index in the case where the problem is grouped but not index dependend

**Comment by joernweissenborn** [comment]
The Unification is also not possible I found after some thinking, since there is to much difference in the calculation paths.

**Comment by joernweissenborn** [comment]
the data copy is solved with #471

**Comment by jsnel** [comment]
This should no longer be an issue in v0.3.0.
