### ISSUE TITLE
Parsing parameter relations with  numexpr or sympy

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#481]
### Description

@joernweissenborn told me that one of the main points to keep `lmfit` (with all the known issues we have with it), is the parsing of parameter relations. Depending on the specs we need there are multiple solutions (all of which will need some string preprocessing, due to the dot syntax e.g. `rates.k1` would need to be changed with a simple string replace to `rates_k1` since it needs to be a valid python variable name, this is ofc just under the hood).

If we just need to evaluate expressions we could use [numexpr](https://pypi.org/project/numexpr/).

If we need to transform a string equation to a function we could use a combination of sympy functions i.e. [`sympify`](https://docs.sympy.org/latest/modules/core.html#sympy.core.sympify.sympify) and [`lambdify`](https://docs.sympy.org/latest/modules/utilities/lambdify.html#sympy.utilities.lambdify.lambdify)

Here is a basic example of how to generate an arbitrary numerical function from a string with sympy
```python
In [1]: import sympy as sym

In [2]: expr = sym.sympify("a*exp(2*x)")

In [3]: expr.free_symbols
Out[3]: {a, x}

In [4]: expr_func = sym.lambdify(expr.free_symbols, expr=expr, modules="numpy")

In [5]: expr_func(x=0, a=5)
Out[5]: 5.0

In [6]: expr_func(a=5, x=0)
Out[6]: 5.0

In [7]: import numpy as np

In [8]: expr_func(a=5, x=np.arange(0, 10))
Out[8]:
array([5.00000000e+00, 3.69452805e+01, 2.72990750e+02, 2.01714397e+03,
       1.49047899e+04, 1.10132329e+05, 8.13773957e+05, 6.01302142e+06,
       4.44305526e+07, 3.28299846e+08])
```

An added bonus with `sympy` is expression simplification and latex output e.g. for automated report generation (maybe that would be a nice to have for `pyglotaran_extras` 😉 ).

**Comment by joernweissenborn** [comment]
Lmfit uses [ASTeval](https://newville.github.io/asteval/). It seams easier, since I can do things like:

``` python
from asteval import Interpreter
aeval = Interpreter()

aeval.symtable['group'] = parameter_group # Instance of ParameterGroup

aeval("2*group.get('kinetic.2')")
```
Is something like this possible with sympy?

**Comment by joernweissenborn** [comment]
numexpr also cant have have arbitratry objects as variables. Since out expressions will be simple, I think asteval is the way to go here.

**Comment by joernweissenborn** [comment]
To clarify: the main problem here is that our parameter names are usually not valid python names and there is no bidirectional way to make them valid. we can crazy names like `red_kinetic.7.reverse`, so simply replacing `.` with `_` e.g. won't work.
