### ISSUE TITLE
Create regular expression to validate parameter names and and capture group strings with '$' in user defined expressions for parameter values.

### ISSUE THREAD

**Issue by joernweissenborn** [glotaran/pyglotaran#491]
# Needed regular expressions

1. Validate parameter names
2. Capture references in user defined relation expressions (for inline replacement)

## Regex to validate parameter names 
 e.g. 2. "my_parameter1" or simply "1" 

##  Regex to capture references in user-defined expressions
 e.g.: I have an expression like "$kinetic.1 * exp($kinetic.2)" for example, I want to transform into an expression like "group.get(kinetic.1') * exp(group.get('kinetic.2')"

**Comment by jsnel** [comment]
Extracting references from user defined expressions:
`(\$[\w\d.]+)`
For examples see: https://regexr.com/5jsge

**Comment by jsnel** [comment]
An invalid parameter name matches to \W, if it *doesn't* match, it should be a valid name.
`\W`
Examples: https://regexr.com/5jsrj
