### ISSUE TITLE
Improve test case for spectral constraints and relations

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#509]
The goal would be to catch an error as fixed by [this commit](https://github.com/glotaran/pyglotaran/pull/507/commits/e9f78ddd85a89e129b1ad9ce906a64120f15a4ef).

### Description

The point is to create a test case which runs over more wavelengths (global axis) than there are species (compartments).

**Comment by joernweissenborn** [comment]
This is now done by the integration tests.
