### ISSUE TITLE
Refactor code to make SVD properties optional

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#528]
### Description

As it is a 512kB ascii file can easily turn into a 10MB dataset when all the fitting info, decompositions and other info is added to it. Sure, storage is less of an issue these days, but it should be possible to reduce this somewhat … think of the users running their data analysis through (small shared) data pipelines over (long distance) networks.

**Comment by jsnel** [comment]
Also consider #322, #321, and similar issues.

**Comment by jsnel** [comment]
Switching from a full to an economy SVD already saved some space, this could be further reduced by making the (calculation of and adding of) SVD completely optional. In principle it is only used for plotting / result inspection and could be handled upstream of the result creation and/or made on-demand.

**Comment by joernweissenborn** [comment]
There is already a switch `add_svd` in the saving options. I am not sure if it works, but it should be fairly simple to make it work. I assign to @s-weigand because I decided to not touch io anymore ;P

**Comment by joernweissenborn** [comment]
Btw, consider also if really makes sense for now, I propose to make this 1.0 milestone, since tis just a nice to have. Disk saving is no reason to hold further development.

**Comment by s-weigand** [comment]
This was solved in #966 with the `data_filter` option
