### ISSUE TITLE
Refactor base_model from_dict

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#537]
### Description

Codacy has [correctly identified](https://app.codacy.com/gh/glotaran/pyglotaran/pullRequest?prid=6912966) that the from_dict classmethod of base_model.py is too complex, it should be refactored for readability and maintainability.

**Comment by joernweissenborn** [comment]
This is much better now, don't think it is an issue anymore. Feel free to reopen if it is still to complex on staging
