### ISSUE TITLE
Implement DOAS

### ISSUE THREAD

**Issue by joernweissenborn** [glotaran/pyglotaran#55]
citing @ism200:

regarding the DOAS, the implementation is currently a product of a sine or cosine with and exponential decay convolved with a Gaussian IRF.

see the top of p.3 in

http://www.nat.vu.nl/~ivo/pub/2016/DOASwithChanelleJumperJCP145_174201_DOI_10.1063_1.4966196.pdf

**Comment by jsnel** [comment]
We need the current implementation refined as described in the material and methods of this (open access) paper: 
[van Stokkum et.al, Estimation of damped oscillation associated spectra from ultrafast transient absorption spectra, The Journal of Chemical Physics 145, 174201 (2016)](https://doi.org/10.1063/1.4966196)

Specifically:
![image](https://user-images.githubusercontent.com/3616369/43051069-9f798b70-8e13-11e8-80fa-a408b6824fca.png)

**Comment by joernweissenborn** [comment]
DOAS will move to an extra plugin package.
