### ISSUE TITLE
Reactivate 'IrfDispersion' in CI test

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#585]
Some time ago we deactivated `IrfDispersion` on the CI since it did lead to the CI timing out.
https://github.com/glotaran/pyglotaran/blob/f214d78d6d68d624effad4f2bdaab41b573b866e/.github/workflows/CI_CD_actions.yml#L112

Since then we removed `dask` which did lead to huge performance improvement so the tests should pass again.
@jsnel also wanted to improve the test with sensible starting parameters so it converges quicker.

**Comment by joernweissenborn** [comment]
@s-weigand is it still deactiavated? if not I not I see no reason why not to

**Comment by s-weigand** [comment]
Closed by #786
