### ISSUE TITLE
Use tabulate for table markdown formatting (#556 follow up)

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#587]
Instead of reinventing the wheel (pun semi-intended) and doing the markdown formatting of table-like output ourselves, we should use [tabulate](https://pypi.org/project/tabulate/) which is battle proven (e.g. also used by `pandas`), will reduce "busy work" and improve code readability.

**Comment by joernweissenborn** [comment]
I leave that to you @s-weigand

**Comment by joernweissenborn** [comment]
@jsnel This is a good opportunity to revise the markdown report generation completely. Especially with having PDF reports in mind.

**Comment by s-weigand** [comment]
Added bonus [tabulate also has latex support](https://github.com/astanin/python-tabulate#table-format)
