### ISSUE TITLE
How to handle breaking API changes? (#556 follow up)

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#588]
We recently had some breaking API changes in #556, BUT the package `is an early access release` so "the right way to do it", keeping the old API alive and warning the users that it will be dropped in the future might slow down the development (at least I was told so).
> Warning: This is an early access release, please refer to the usage notice down below prior to committing to use pyglotaran to avoid surprises down the line.

IMHO there are only 2 user-friendly ways and don't forget that we are our own users (e.g. atm we have at least 2 repos that depend on the core  [pyglotaran_extras](https://github.com/glotaran/pyglotaran_extras) and [pyglotaran_examples](https://github.com/glotaran/pyglotaran_examples))
1.) Do it "the right way" and redirect the old API calls to the new ones, warning users.
2.) Use a "dummy API" which breaks, but tells the users what the new way is.

I'm making this an issue now because IMHO this is a workflow pattern that will influence future development and having a set way to do things frees us from the mental load to think about it each time (e.g. think back of the times before we had `pre-commit` doing all the formatting and lining for us). 
Also, a more graceful way to handle breaking changes to the API profits code in our own organization.

**Comment by jsnel** [comment]
Either option will work for me. Both are better than just breaking existing user's script and let them guessing where the problem may be.
