### ISSUE TITLE
Include fit of actual data in tests

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#63]
This is an example which can be turned into a nosetest: 
https://github.com/glotaran/glotaran/blob/variable_naming_refactor/tests/python/fit_data_streakdata_ascii_seq.py

**Comment by joernweissenborn** [comment]
@s-weigand knows best.

Related to #71

**Comment by s-weigand** [comment]
Guess this can be closed since we now got the integration tests from the [examples repo](https://github.com/glotaran/pyglotaran-examples) action.
