### ISSUE TITLE
Estimate a scaling number per wavelength

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#643]
### Description

In kinetic-spectrum models, especially with TCSPC data, it is sometimes needed to estimate a scaling parameter, not (just) per dataset, but per wavelength instead. The 'scale' parameter in the dataset descriptor becomes a parameter vector equal to the number of wavelengths in that dataset, rather than a single parameter.

**Comment by joernweissenborn** [comment]
This is possible since https://github.com/glotaran/pyglotaran/commit/803444f49c24c8fc3dba8a0020476b286923bf2f
