### ISSUE TITLE
Create Glotaran developer guide

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#66]
For (future) contributors an easy to go to **developer guide** should be available that helps them get started contributing to Glotaran and informs them about things like code style standards we adhere to.

**Comment by stanleyextreme** [comment]
Dear Joris - I just happened to find your python implementation of Glotaran. I wish I could contribute but I'm not much of a python programmer. Do you need help proof-reading documentation?   
Sincerely,
Bob Stanley, Chemistry Department, Temple University

**Comment by s-weigand** [comment]
We have got a [contibuting guide](https://github.com/glotaran/pyglotaran/blob/main/CONTRIBUTING.rst) and it will need constant adaption as we go. So this issue can be closed.
