### ISSUE TITLE
♻️ Make '_get_area' return a single value instead of an array

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#746]
In #740 `_get_area` returns a `np.ndarray`, which is only used to call `np.sum` on it and then discarded.
Given the name, it would make more sense for `_get_area` to return the sum directly.
Also, this change pretty much wouldn't have any impact on the computation itselfe.

Ref: https://github.com/glotaran/pyglotaran/pull/740#discussion_r669197788

**Comment by joernweissenborn** [comment]
well, it is like this for debugging reasons. I would rather rename the function `_get_area` to `_get_clp_sclice`.
