### ISSUE TITLE
💬 Add Issue Triage 

### ISSUE THREAD

**Issue by joernweissenborn** [glotaran/pyglotaran#749]
We have tons of old issues, a bot ~~based on Dangerfile~~ could help.

**Comment by s-weigand** [comment]
Needs more information on what we want and need to do with that.
If we just want to close stale issues we could use [Stale](https://github.com/marketplace/stale).
If we want to add labels based on the text there are also bots for that.
But we also use issues as a kind of backlog for future ideas... so it needs a clearer description.

**Comment by s-weigand** [comment]
@joernweissenborn This is still missing information, feel free to close it if not relevant anymore
