### ISSUE TITLE
✨ Implement spectrotemporal models as implemented in paramGUI

### ISSUE THREAD

**Issue by joernweissenborn** [glotaran/pyglotaran#750]
A spectrotemporal model for fitting time-resolved spectroscopy data is described in the paper
**Global and target analysis of time-resolved spectra** DOI: [10.1016/j.bbabio.2004.04.011](https://doi.org/10.1016/j.bbabio.2004.04.011)
 
A public implementation is available in the R package [paramGUI](https://github.com/glotaran/paramGUI).

This issue is about implementing equivalent functionality, but implemented using megacomplex composition.

A repository for validation example code can be found here: [pyglotaran-validation](https://github.com/glotaran/pyglotaran-validation/) this contains the (reference) [paramGUI examples](https://github.com/glotaran/pyglotaran-validation/tree/main/paramGUI) to test the implantation against.

**Comment by jsnel** [comment]
This has been implemented on staging. Validation of functionality was performed using scripts found in the [pyglotaran-validation](https://github.com/glotaran/pyglotaran-validation) repository.

Issue should be closed when staging is merged to main, see: #777

**Comment by jsnel** [comment]
Staging was merged into main with #778 so it's in, and it was validated against [paramGUI](https://github.com/glotaran/pyglotaran-validation/tree/main/paramGUI).
