### ISSUE TITLE
🚧 Naming conventions for boolean switches

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#755]
For consistencies sake and also easier naming for use, we should come up with some naming convention.
While reviewing #747 I came across some misleading names like `object.full_model` and `object.global_model`, which are just boolean switches.
IMHO going with a pattern like `is_<something>` makes it a lot easier to read the code and quickly see what is going on.

**Comment by jsnel** [comment]
Some work for this is done on the staging branch, is this still an issue? If so the PR which ultimately merges staging back into main should be listed as a Linked pull request to close this issue.

**Comment by s-weigand** [comment]
Not sure if we are consistent across the whole package (`main` + `staging`).

Also to prevent bugs like https://github.com/glotaran/pyglotaran/pull/747#discussion_r670785543

It is a good practice to use identity comparison against the boolean singletons
```python
if is_something() is True:
    ...
```

**Comment by s-weigand** [comment]
This will be done inclement, when ever we are touching code or in a big refactor PR dedicated to this issue.
