### ISSUE TITLE
🐛 Deprecate save Result as yml

### ISSUE THREAD

**Issue by joernweissenborn** [glotaran/pyglotaran#768]
The problem is that it tries to serialize e.g. the covariance matrix. It would be best overwritte the state getter and setter.

**Comment by joernweissenborn** [comment]
Please make PR against staging and merge asap.

**Comment by s-weigand** [comment]
@joernweissenborn Isn't the yml parser your baby? 😝

**Comment by joernweissenborn** [comment]
I will fix this in in project feature

**Comment by jsnel** [comment]
Saving results entirely as yml doesn't make sense, a hybrid approach is needed whereby the structure and simple properties are saved as yml but anything matrix like is saved as binary blobs (.e.g nc files) which are referenced by a path name only.

**Comment by joernweissenborn** [comment]
So, as I see it now, we have it like this:

You give a yaml, it takes yaml. You give folder, then it will look for `glotaranresult.yml` in the folder and use yaml to load it. So where is the issue left?

**Comment by s-weigand** [comment]
Made the preferred way to save results in #966 (now the serialized yaml only links to other files) and the folder plugin was demoted to be only used internally.
