### ISSUE TITLE
🐛 Compartment ordering not not consistent everywhere (problem in spectral penalties)

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#787]
### Version information

- pyglotaran version: staging

### Describe the bug

During a debugging session (@jsnel, @s-weigand) the following was found:
- equal area penalties are applied differently (compartment order) between `0.4.1` and `staging` (failing `ex_two_datasets` and possibly `simultaneous_analysis_6d_disp`); because clps and clp_labels are not aligned the areas of the wrong spectra are calculated (in some cases where e.g. s1,s2,s3 -> s1,s3,s2 or similar)
- problems in `simultaneous_analysis_6d_disp` might be due to missing noise and/or the differences in how weights are applied

_Originally posted by @s-weigand in https://github.com/glotaran/pyglotaran/issues/754#issuecomment-899154493_

**Comment by jsnel** [comment]
This remains an issue (on staging) after merging #788, investigating...

**Comment by s-weigand** [comment]
Looks like the github autoclose doesn't work properly.
@jsnel Did #799 resolve that issue? If yes feel free to close it.

**Comment by jsnel** [comment]
I think auto merge works when something is merged into the main branch, and this was only merged to staging.
There are several issues that should auto close when staging is merged into main.

**Comment by jsnel** [comment]
This was resolved in #799 and got merged with #778 into main.
