### ISSUE TITLE
🐛 CoherentArtifactMegacomplex.finalize_data crashes due to wrong dimensions

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#793]
### Version information

- pyglotaran version: staging
- Python version: all
- Operating System: all

### Describe the bug

When using a `CoherentArtifactMegacomplex` pyglotaran crashes while creating the result, when trying to assign `coherent_artifact_concentration`

https://github.com/glotaran/pyglotaran/blob/b28179970cd7ab0d9b7e276c3d25ff7dae69e7cd/glotaran/builtin/megacomplexes/coherent_artifact/coherent_artifact_megacomplex.py#L76-L79

This is due to the fact that `dataset.matrix.sel(clp_label=self.compartments()).values` has the dimensions (`global_dimension`, `model_dimension`, `"coherent_artifact_order"`) and we try to create a `DataArray` of dimensions (`model_dimension`, `"coherent_artifact_order"`).

### To Reproduce

Run `pyglotaran_examples/ex_doas_beta/ex_doas_beta.py`from  [this commit](https://github.com/s-weigand/pyglotaran-examples/commit/d4460b6045c6838523249255d436603fd1c96471)

### Expected behavior

Result gets created without crashing.

### Possible Solutions

1. Save all data with the full dimensions (`global_dimension`, `model_dimension`, `"coherent_artifact_order"`)
2. Only use a single `global_dimension` e.g. `dataset.matrix.sel(clp_label=self.compartments()).values[0, :, :]`
3. Use an aggregation function along the `global_dimension` e.g. `dataset.matrix.sel(clp_label=self.compartments()).sum(global_dimension).values` or `dataset.matrix.sel(clp_label=self.compartments()).mean(global_dimension).values`

**Comment by s-weigand** [comment]
@joernweissenborn Wanted to add more tests for different code paths and fix this issue.

**Comment by joernweissenborn** [comment]
The first solution please, HDD space is cheap so we save everything, NEVER averages/means.

**Comment by s-weigand** [comment]
closed by #808
