### ISSUE TITLE
♻️ Refactor tests to be more readable (follow-up to #807)

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#815]
### Is your feature request related to a problem? Please describe.

Currently, most of the tests use `Model.from_dict` with 20+ lines dicts to define the model and this makes it harder to spot the differences between tests and to detect [problems in tests](https://github.com/glotaran/pyglotaran/commit/dce7f0b90b39c5d89eb7f7584fbdc70ad76da7fa).
#807 implements a simple draft of how tests could be refactored and made more readable.

### Describe the solution you'd like

While tests should be verbose, they should also be readable and understandable.
Thus an autogenerated model dict generated by only the needed parameters as proposed in #807  would help to simplify tests and make it a lot easier to spot the differences between tests and detect errors.

Since this would be a test refactor it should only change:
1) Tests which use `Model.from_dict`
1) The [model dict generators in `glotaran.testing`](https://github.com/glotaran/pyglotaran/pull/807/files#diff-2a848be76af03a6c04d6c85d863949706ef81a2704f06eafbdf414c804e29db6)

### Additional context

The tests that could quickly be changed  are listed in https://github.com/glotaran/pyglotaran/pull/807#issuecomment-917754629

**Comment by s-weigand** [comment]
Taken by @fidelak

**Comment by jsnel** [comment]
After some further consideration we realize that we currently don't have "good first issues" that don't require some amount of domain knowledge, so I removed that label. See also: https://github.com/glotaran/pyglotaran/issues/837 

If you did manage to do something already @fidelak please let us know, but if you didn't start yet then no worries, we'll pick this up internally.
