### ISSUE TITLE
✨ Add info about each optimization step to the result object

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#819]
### Description / User Story

As a user I would like to have some information about the state of my optimization at each step of the iteration, e.g. starting with the residual and the parameter list at each step of the optimization (observed as calls to the compute residual function by the optimizer). 

### Proposed solution to consider

To the results object I'd like to add the list of parameters currently stored in the _parameter_history attribute of the problem class.

### Additional context

Partially covered described by #440.

The idea is that for the first 'feature complete' release you'd like to establish a somewhat final API. We might not be able to put everything we want in there from the start, but at least the user can expect something to be there (that can then be expanded in the future).

**Comment by joernweissenborn** [comment]
@s-weigand @jsnel This is more complex, but possible. We basically need to rename `glotaran.parameter.ParameterHistory` to `glotaran.otimization.OptimizationHistory`. Then we add the cost it and add this as field for CSV. But I rather have this in 0.6, please move it. I wat to do it myself in scope of project.

**Comment by s-weigand** [comment]
Related issues #233 #774 #440
