### ISSUE TITLE
✨ Support for additional data for megacomplex calculate_matrix

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#820]
### Feature description 

Specifically to solve the use cases of simplifying specifying a measured IRF or a spectral guidance spectra without hacking it in via datasets.

**Comment by joernweissenborn** [comment]
As discussed with @jsnel we need slightly different solution for spectral guidance.

**Comment by joernweissenborn** [comment]
See #822 dor spectral guidance
