### ISSUE TITLE
♻️ Refactor DatasetModel to use properties 

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#828]
### Version information

- pyglotaran version: main (2f1afe78db8b0d6a0a4b75c86f09e35f7428ad4a)
- Python version: all
- Operating System: all

### Describe the refactoring

Currently `DatasetModel` uses a lot of `get_` and `set_` methods

https://github.com/glotaran/pyglotaran/blob/2f1afe78db8b0d6a0a4b75c86f09e35f7428ad4a/glotaran/model/dataset_model.py#L157-L163

The same functionality could be achieved using [properties and setter.](https://www.python-course.eu/python3_properties.php)

Using `get_` and `set_` is c++ like from the 90's, we have nice syntax sugar let's use it.

```python
In [4]: import this
The Zen of Python, by Tim Peters

Beautiful is better than ugly.
...
```

### Additional context
Besides refactoring of `glotaran/model/dataset_model.py` this will need additional changes to the tests and where it is used.

**Comment by fidelak** [comment]
Would you mind if I worked on this one?

**Comment by s-weigand** [comment]
@fidelak Sorry, I just talked to @joernweissenborn and this issue is quite tricky since it requires to interact with our runtime "decorator magic" (code that writes code).
But #807 should be a good first issue.

**Comment by fidelak** [comment]
@s-weigand I assume you're talking about the follow up in #815? I will give it a shot

**Comment by s-weigand** [comment]
Oops, yes I meant #815 ofc 😅 
@fidelak Thanks for contributing 😄
