### ISSUE TITLE
✨ Time for a new logo

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#832]
### pyglotaran needs a new logo

With the upcoming new 'major' release v0.5.0 it is time to refresh the branding. 
We have been piggy-backing on the old glotaran logo, which has been fine, but I think pyglotaran deserves its own logo, with a more modern look.

### Describe the solution you'd like

For the new logo I'd like to see a more square with rounded edges style, giving us a more modern look.
I'd like to retain the aspect of the cyclic nature in any Problem Solving Environment (PSE), e.g. the parameter estimation loop, the model adjustment loop, etc. as is currently represented by the circular arrows. But rather than 3 arrows in a circle, I suggest we use 4 going around in a square with rounded edges. 

![Screenshot 2021-09-19 082358](https://user-images.githubusercontent.com/3616369/133920263-45915088-1f80-4e83-a004-5d39b1d0189b.png)

### Requirements

The graphics should be vector-graphics (e.g. .svg) easily editable in Inkscape or another open source tool and not required proprietary or licensed software to modify.  

Main logo
- Square with rounded edges
- The square is made of rounded edges
- If aesthetics requires it the arrow head can only point inward
- Should retain the colorful design
- Should retain the GTA abbreviation, but add 'py' 
- Should still be recognizable at 32x32

High contrast logo
- Like the main logo
- Less color full
- Higher contrast (looks good when converted to monochrome)

Icon logo:
- Should still be recognizable at 16x16
- Like the main logo
- Arrows are less important
- Colors are less important

**Comment by joernweissenborn** [comment]
can we postpone this to 0.6? Or 1.0?

**Comment by s-weigand** [comment]
I like 2 the most and 2nd place for me is 3.

**Comment by jsnel** [comment]
During the last poll most people preferred 3 (or 2). I think for simplicity lets stick with the monochrome font for the text, at least for the application icon. We can then always design a more fanciful logo that can be used for posters or websites.

To further improve logo 3, I suggest we vectorize the rainbow graphics border to pure svg using an approach outlined [here](https://stackoverflow.com/questions/18206361/svg-multiple-color-on-circle-stroke) and shown [here](http://jsfiddle.net/Weytu/) (just translate the circle to a square with rounded edges. Perhaps change the stroke width a bit, and darken the font.

![image](https://user-images.githubusercontent.com/3616369/161403212-f9fe99ad-e8d0-4d05-88ad-3bb7d2668e9f.png)


Then for going to the low res logo (one that is still recognizable at 48, 32, 24, and 16 pixels, @s-weigand and I imagine replacing the GTA letters (which are organized in a triangle) with an actual triangle and the py text with a dot in the same position. This way the logo still resembles the original. e.g.:

![g97-w](https://user-images.githubusercontent.com/3616369/161403388-52d02ea7-f622-4a7d-aeb3-6d7133bfa7f0.png) (white bg)
![g97-t](https://user-images.githubusercontent.com/3616369/161403390-2b6ab52f-5ef1-481d-a811-e7010421fac0.png) (transparent bg)
![g97-k](https://user-images.githubusercontent.com/3616369/161403437-74b4be94-99c0-4e07-889e-80fa33efcadb.png) (black bg)

**Comment by jsnel** [comment]
@s-weigand please use the assets and turn it into a pure .svg logo (high res and low res version).

**Comment by s-weigand** [comment]
Just as a note I will use [this tool](https://github.com/shakiba/svgexport) for the SVG -> PNG conversion since it renders the SVG images with puppeteer which uses chromium under the hood.
All tests with `cairo` and `want` didn't properly work due to missing features of the SVG specs (`mask` and `foreignObject`)
