### ISSUE TITLE
✨ Make non_negative_least_squares an option per dataset (group)

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#838]
## General description of your issue

The non_negative_least_squares (NNLS) optimization option is typically used when analyzing data which is known to be strictly positive (e.g. fluorescence data), but not when the data can be positive or negative (e.g. transient absorption spectroscopy, or pump-probe data). In most use cases this works perfectly fine, but what if we want to a simultanous analysis of *both* types of datasets. Then for one group of datasets (e.g. 3 streak datasets with T1, T2, T4) we might want to apply the NNLS constraint, but not for the other group of datasets (e.g. 2 pump-probe datasets). 

## Describe the solution you'd like

The optimization option `non_negative_least_squares` is used to switch between different `problem._residual_function`s, for which currently supported are `residual_nnls` if `non_negative_least_squares=True` and `residual_variable_projection` if `non_negative_least_squares=False`. Instead of making the a global optimization option, one could keep track for which dataset (group) a particular function should be used.

The call to `problem._residual_function` curently appears 4 times (grouped/ungrouped and index dependent/independent). 

### A case study
As a practical example. Imagine a simultaneous analysis of 3 fluorescence dataset, with a shared spectral axis (e.g. 400-800 nm, every 10nm), but different time windows (-0.1 to 0.5 ns per 0.001, -0.5 to 1.2 ns per 0.05 ns, -1 to 5 ns, per 0.01 ns) . The datasets are fitted with the same model e.g. (FS1, FS2, FS3) with rates (k1, k2, k3). The datasets are grouped along the spectral axis (the compartments FS1, FS2, FS3 are linked across the 3 dataset). For these datasets we wish to use `non_negative_least_squares=True`.

Then we have 2 transient absorption (TA) spectroscopy datasets, which have a partially overlapping mostly shared spectral axis (e.g. 300-600, 500-800, every 10 nm) and identical time windows (-0.1 to 1ns, per 0.0005 ns). This datasets has 4 *different* compartments (TA1, TA2, TA3, TA4), with 4 rates, kS2, k1, k2, k3. The rates k1, k2, k3 are the **same** rates as the ones in the fluorescence data, KS2 is a rate unique to the TA datasets . The two transient absorption datasets are also grouped along the spectral axis (where they overlap), and the compartments TA1, TA2, TA3, TA4, are linked between both dataset . For this dataset we wish to use `non_negative_least_squares=False`.

Even though all datasets have some part of the spectral axis in common, e.g. between 400 and 800 nm, the fluoresce datasets should *not* be grouped together with the transient absorption datasets - which allows us to call different optimization _residual_function for the two different groups, even when evaluating the residual at possibly the exact same wavelength. This is also implied by the fact that there are different compartments fitted in both sets of datasets (FS1, FS2, FS3 vs TA1, TA2, TA3. TA4) 
which only linked kinetically through common rates k1, k2, k3, but not spectrally. 

It should be possible to simulate the above problem descriptions separately, generate a total of 3+2=5 datasets, and then attempt a combined analysis of these data as the case study described here.

**Comment by joernweissenborn** [comment]
done in 0.5
