### ISSUE TITLE
Get a DOI for pyglotaran

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#84]
Since i just saw that possibility at the [lmfit repo](https://github.com/lmfit/lmfit-py) i just leave a reminder here, that glotaran could get a DOI from [zenodo](https://zenodo.org/) .

**Comment by jsnel** [comment]
pyglotaran has a DOI since v0.3.0, the following URL will always map to the latest version:
[https://doi.org/10.5281/zenodo.4534043](https://doi.org/10.5281/zenodo.4534043)
