### ISSUE TITLE
✨ Support all everything what pandas dataframe supports for parameter io

### ISSUE THREAD

**Issue by joernweissenborn** [glotaran/pyglotaran#844]
### Is your feature request related to a problem? Please describe.

At the moment we store actually `tsv` when we say we store `csv`. We should actually save what we say we save.

### Describe the solution you'd like

The current package `glotaran.builtin.io.csv` should be renamed to `glotaran.builtin.io.pandas`. It should levarage the `ParameterGroup` functions `from_df` and `to_df` to implement all de-/serialization features provided by `pandas.df` (maybe even excel or at least `ods`).

### Describe alternatives you've considered

I don't think there is alternative for pandas for this.

### Additional context

We don't have a way to configure saving at plugin implementation, so please choose sensible defaults for each format.

**Comment by joernweissenborn** [comment]
@glotaran/maintainers maybe a good first issue? I leave the triage to you.

**Comment by s-weigand** [comment]
@Bratapfel2000 Looks like this is right in your ballpark 😄

**Comment by Bratapfel2000** [comment]
Alright, sounds good!

**Comment by s-weigand** [comment]
Closed in #896
