### ISSUE TITLE
✨ Create Clp Guidance

### ISSUE THREAD

**Issue by joernweissenborn** [glotaran/pyglotaran#846]
### Is your feature request related to a problem? Please describe.

This is a request by @ism200. Basically, sometimes a virtual dataset is added to the analysis to provide guidance for the clp estimation.

### Describe the solution you'd like

This is tricky to solve. Semantically, the guidance spectrum is dataset by it's own. This means it has to be representented as a special dataset.

An idea woud be to introduce an option for a dataset model called `clp_guide`. This will mean that this dataset is allowed to have no megacomplexes (ectually forbitten to have one). It will just return an array of ones, depending of it is index dependent it is one.

I think this is best solved along the path to make mixed nnls and varpro fitting.

### Additional context

There should be a case study for that.

**Comment by s-weigand** [comment]
Closed in #1029
