### ISSUE TITLE
♻️ Rename dataclass_helper functions and arguments with more sensible names

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#853]
In the review of #841, [it was suggested](https://github.com/glotaran/pyglotaran/pull/841#discussion_r721007135) to rename functions and arguments related to the custom dataclass helper functions, not to be confused with the python builtin.

**Comment by jsnel** [comment]
Partially resolved, but still an issue in some places:
https://github.com/glotaran/pyglotaran/blob/main/glotaran/project/dataclass_helpers.py#L167
`def asdict(dataclass: object, folder: Path = None) -> dict[str, Any]:`
