### ISSUE TITLE
♻️ Refactor Result and Scheme loading to to use 'file' fields

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#858]
Adding additional fields look clunky and doesn't add extra value apart from loading a file https://github.com/glotaran/pyglotaran/pull/841#pullrequestreview-775672503

>  ✊ There must be a better way

**Comment by joernweissenborn** [comment]
Is this really needed for 0.5?

**Comment by s-weigand** [comment]
Yap, we are going to introduce a new API just to deprecate it in the next release...
