### ISSUE TITLE
🐛 'dataset_groups' not shown in model markdown

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#885]
### Version information

- pyglotaran version: main (d05c042a6e4dffeac556d117f30a7b52f4e2b98f)
- Python version: 3.8
- Operating System: Ubuntu 20.4

### Describe the bug

The markdown repr for models, misses `dataset_groups` as a section.

### To Reproduce

- Define any model
- Look at `model.markdown()`

### Expected behavior

The `dataset_groups` are shown, especially since `default`  is mentioned in `dataset`.

**Comment by joernweissenborn** [comment]
This is because `dataset_group` is not a `glotaran.model.item` decorated object. I don't want to elaborate on why, but it is possible, but hard, to make it one.

@s-weigand Do you think it feasible to add special code to `Model.markdown` for the groups?

**Comment by s-weigand** [comment]
@joernweissenborn We already special case `Megacomplex Types`, so why not do the same for `dataset_group`?
