### ISSUE TITLE
🐛 save_result crashes on Windows if input data are on a different drive than result

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#924]
### Version information

- pyglotaran version: 0.5.0
- Python version: all
- Operating System: Windows

### Describe the bug

While upgrading the `pyglotaran-examples` not to use deprecated functionality, I encountered a serious bug where `save_result` crashes when saving the scheme.

```python
ValueError: path is on mount 'D:', start on mount 'C:'
```

The problem is that I have the `pyglotaran-examples` at `D:\git` and the results are saved under `%USERPROFILE%` which is on the `C:\` drive which lets `relpath` crash.

https://github.com/glotaran/pyglotaran/blob/89046e0a95117d63336f5cdb637bf8acf52addb2/glotaran/project/dataclass_helpers.py#L197-L201

https://github.com/glotaran/pyglotaran/blob/89046e0a95117d63336f5cdb637bf8acf52addb2/glotaran/utils/io.py#L181

### To Reproduce

Copy the `pyglotaran-examples` to a different drive than the `C:\` drive and run:

```console
python scripts/run_examples.py sim-3d-disp 
```

### Expected behavior

No crash!

### Additional context

We have multiple options to fix this:
1. Copy the data to a path relative to `scheme.yml` and warn the user
2. Use absolute paths and warn the user
3. Overwrite `scheme.data` with `result.data`, since the result data also contain the original data and are saved relative to `scheme.yml`

@joernweissenborn @jsnel  What do you think?

`1.` or `2.` (or another solution) need to be implemented to make `file_loadable_field` robust, `3.` is optional and a disk space-saving option if we choose to go with `1.`.

**Comment by joernweissenborn** [comment]
So I think the solution should be windows specific and we should go for absolute path in such cases. So option 2 without warning it is (I see no reason for a warning, windows users are not familiar with relative paths anyway).

So result data does NOT include the original data anymore. We can add an option `SavingOption` to include the original data, but this should not be default.

To create reproducible results with the original data users should put them close to each others. The canonical way for this should be using project, which will also get an export functionality.
