### ISSUE TITLE
✨ Add include tag to yaml parser for parameters and models

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#955]
This will open the opportunity to define more modular models and parameter files.
See the discussion in https://github.com/glotaran/pyglotaran/pull/930

**Comment by jsnel** [comment]
To be re-evaluated in the context of recent model language developments. 

Also, I feel this issue will be made partially obsolete with the introduction of model items.

Will revisit for v0.8.0 milestone.
